P.register("cvfVersion",function(){return{version:"0.1.0.0-2024-06-26"}});"use strict";
P.when("A","cvfFormDataGenerator","cvf-client-side-counters-util","ready").register("cvf-account-switcher",function(a,l,b){function m(b,c){b.preventDefault();var d=l.retrieveFormData(b.target),g=d.inputData.serializeArray();g.push(e(b.target));a.ajax(window.location.protocol+"//"+window.location.host+d.requestPath,{method:"POST",params:g,success:c,error:f})}function e(a){a=g(a);var b=a.attr("name");b||(b=a.closest(".cvf-account-switcher-sign-out-link").attr("data-name"));var c=a.attr("value");c||
(c=a.closest(".cvf-account-switcher-sign-out-link").attr("data-value"));return{name:b,value:c}}function f(b,c,d){a.trigger(p.error,d)}function d(a){var b=/([^@\s]+)@([a-zA-Z0-9_-]+)(\.[a-zA-Z0-9._-]+)/ig.exec(a);if(null!==b){a=b[1];a=g.trim(a);var c=a.length;if(1!==c){for(var d=a.charAt(0),e=0;e<c-2;e++)d+="*";a=d+=a.charAt(c-1)}a+="@";d=b[2];d=g.trim(d);c=d.length;d=d.charAt(0);for(e=0;e<c-1;e++)d+="*";return a+d+b[3]}b=g.trim(a);a=b.length;if(!(4>=a)){c="";for(d=0;d<a-4;d++)c+="*";b=c+b.substr(a-
4,a-1)}return b}function c(){0===g(".cvf-account-switcher-check-mark:visible").length&&(g(".cvf-account-switcher-check-mark-area").remove(),g(".cvf-account-switcher-profile-details").toggleClass("cvf-account-switcher-profile-details cvf-account-switcher-profile-details-after-account-removed"))}function h(d){var c=new URLSearchParams(window.location.search);c.delete("switch_to_cid");c.has("errorCodes")||c.append("errorCodes","ACCOUNT_SWITCH_FAILED");b.addMetricCount(d);a.trigger(p.error,"automaticAccountSwitchFailure");
window.location.search=c}function q(){if(0!==g(".cvf-switch-to-cid").length)try{b.startMetricTimer(n.latency);var c=g(".cvf-switch-to-cid")[0].getAttribute("value");g(".cvf-automatic-switch-"+c)[0].click();setTimeout(function(){h(n.failureTimeout)},7E3);a.trigger(p.success,"automaticAccountSwitchSuccess");return!0}catch(t){h(n.failureClicking)}finally{b.endMetricTimer(n.latency)}return!1}var g=a.$,p={success:"cvf:account_switcher:success",error:"cvf:account_switcher:error"},n={latency:"AutomaticAccountSwitch_Latency",
failureClicking:"AutomaticAccountSwitch_FailureClicking",failureTimeout:"AutomaticAccountSwitch_FailureTimeout"};(function(){var a=g("#ap-account-switcher-container")[0],b=window.MutationObserver||window.WebKitMutationObserver;if(void 0!==a&&void 0!==b){var d=new b(function(a){for(var b=0;b<a.length;b++)if(null!==a[b].addedNodes){q()||c();d.disconnect();break}});d.observe(a,{attributes:!0,childList:!0,characterData:!0,subtree:!0})}})();(function(){g(".cvf-account-switcher-sign-out-link").live("click",
function(b){m(b,function(e){if(e.redirectUrl)window.location=e.redirectUrl,a.trigger("cvf:account_switcher","redirectOnSignOut");else if(e.succeeded){var f="."+g(b.target).attr("class").match(/cvf-account-switcher-account-group-\w+/g)[0];g(f+"-hide").hide();g(f+"-name").text(g("#cvf-account-switcher-sign-out-replace-text").text());g(f+"-claim").text(d(g(f+"-claim").text()));g(f+"-image").replaceWith(g("\x3cdiv /\x3e").append(g("#cvf-account-switcher-sign-out-replace-image").clone().removeClass("cvf-hidden")).html());
g(f+"-button").removeClass("cvf-widget-btn-val cvf-widget-btn-verify-account-switcher");e=e.switchedAccountId;void 0!==e&&g(".cvf-account-switcher-account-group-"+e+"-check-mark").show();c();window.location.reload()}else a.trigger(p.error,e)})})})();return{automaticAccountSwitch:q}});"use strict";
P.when("A","cvfInputValidatorConfig","ready").register("cvfInputValidator",function(a,l){return{getValidationResult:function(b){var m=!0,e=[],f=[];l.forEach(function(d){var c=a.$(d.invalidFieldAlertSelector),h=a.$(d.emptyFieldAlertSelector);d=b.find(d.inputSelector);d[0].required&&!d.val().trim()?(m=!1,0<h.length?(e.push(h),0<c.length&&f.push(c)):0<c.length&&e.push(c)):(0<h.length&&f.push(h),h=d[0].checkValidity&&!d[0].checkValidity(),m=m&&!h,c.length&&(h?e.push(c):f.push(c)))});return{isValid:m,
activeAlerts:e,inactiveAlerts:f}}}});"use strict";P.when("A","ready").register("cvfInputValidatorConfig",function(a){return[{inputSelector:".cvf-widget-input-code",invalidFieldAlertSelector:".cvf-widget-invalid-code-alert",emptyFieldAlertSelector:".cvf-widget-empty-field-alert"}]});P.register("a-sheet-wrapper",function(){return null});"use strict";
P.when("A","cvfFormDataGenerator","ready").register("cvfCaptcha",function(a,l){a=a.$;0===a(".cvf-widget-input-captcha").children("input").length?(a(".cvf-widget-input-captcha").attr("autocapitalize","off"),a(".cvf-widget-input-captcha").attr("autocorrect","off")):(a(".cvf-widget-input-captcha").children("input").attr("autocapitalize","off"),a(".cvf-widget-input-captcha").children("input").attr("autocorrect","off"))});"use strict";
P.when("A").register("cvf-client-side-counters-util",function(a){function l(a,m){var b=window.ue;b&&"function"===typeof b.count&&(m||(m=(b.count(a)||0)+1),b.count(a,m))}return{incrementCounter:function(a){l(a)},insertCounter:l,addMetricCount:function(a){window.ue&&"function"===typeof window.ue.count&&window.ue.count(a,1)},startMetricTimer:function(a){window.uet&&"function"===typeof window.uet&&window.uet("bb",a,{wb:1})},endMetricTimer:function(a){window.uex&&"function"===typeof window.uex&&window.uex("ld",
a,{wb:1})}}});
P.when("A","3p-promise","a-alert","codeResendTimer","cvf-client-side-counters-util","sms-retriever-handler","ready").execute("client-sms-request-controller",function(a,l,b,m,e,f){function d(){a.show("#cvf-otp-autoread-progress");e.incrementCounter(u.SHOW_AUTOREAD_WIDGET);var b=c();x.delegate("#cvf-input-code","input",function(){clearTimeout(b);a.hide("#cvf-otp-autoread-progress");var c=n("#cvf-auto-read-status");c.val()!==t.AUTOREAD_TIMEOUT&&c.val()!==t.AUTOREAD_SUCCESS&&(e.incrementCounter(u.CANCEL_AUTOREAD_WIDGET),c.val(t.AUTOREAD_CANCELLED))})}
function c(){return setTimeout(function(){var c=n("#cvf-auto-read-status");a.hide("#cvf-otp-autoread-progress");e.incrementCounter(u.AUTOREAD_WIDGET_TIMEOUT);c.val(t.AUTOREAD_TIMEOUT);b("#cvf-otp-autoread-timeout").show()},3E4)}function h(b){y=b;b=n("#cvf-auto-read-status");k&&b.val()!==t.AUTOREAD_TIMEOUT&&b.val()!==t.AUTOREAD_CANCELLED&&(b=y,n("#cvf-auto-read-status").val(t.AUTOREAD_SUCCESS),n("#cvf-input-code").val(b).trigger("input"),a.show("#cvf-otp-autoread-success"),x.submit())}function q(a){m.createTimer(Number(a.timeRemaining),
n("#resend-timer-message-id").val(),n("#resend-timer-complete-id").val().replace(/"/g,""),"timer","timer",!1);a=n("#wait-resend-auto-read");a.submit(function(a){a.preventDefault()});n(".wait-one-minute-continue").click(function(){z.location.reload()});a.removeClass("aok-hidden");x.addClass("aok-hidden")}function g(){b("#otp-request-failed-alert").show();n("#cvf-input-code").attr("disabled","disabled").addClass("a-form-disabled");n("#cvf-submit-otp-button").addClass("a-button-disabled");n("#cvf-resend-link").unbind().click(function(){z.location.reload()})}
function p(b){a.get(b,{success:function(a){a.wait?(e.incrementCounter(u.WAIT_RESEND),q(a)):a.redirect?(e.incrementCounter(u.REDIRECT),z.location.replace(a.redirect)):(a=a.smsFormat)?(e.incrementCounter(u.RECEIVED_FORMAT+":"+a),"androidAutoReadSmsWithAppHash"===a&&(k=!0,d(),y&&h(y))):(e.incrementCounter(u.FORMAT_NOT_RECEIVED),console.error("Failed to receive sms format"))},error:function(a,b,c){e.incrementCounter(u.AJAX_SMS_REQUEST_FAILED+":"+c);g();console.error("Ajax request failed",c)}})}var n=
a.$,z=this;f=[f];var t=Object.freeze({AUTOREAD_SUCCESS:"autoreadWidgetSuccess",AUTOREAD_CANCELLED:"autoreadWidgetCancelled",AUTOREAD_TIMEOUT:"autoreadWidgetTimeout"}),u=Object.freeze({SHOW_AUTOREAD_WIDGET:"OTPAutoReadShowWidget",CANCEL_AUTOREAD_WIDGET:"OTPAutoReadCanceWidgetForManualInput",AUTOREAD_WIDGET_TIMEOUT:"OTPAutoReadWidgetTimeout",RECEIVED_FORMAT:"OTPAutoReadReceivedFormat",FORMAT_NOT_RECEIVED:"OTPAutoReadFormatNotReceived",REDIRECT:"OTPAutoReadClientRedirect",AJAX_SMS_REQUEST_FAILED:"OTPAutoReadAjaxSmsRequestFailed",
WAIT_RESEND:"OTPAutoReadWaitResend"}),w=a.state("autoReadAttrs");if(w&&w.isClientDrivenOtpSendingEnabled){var A=w.arbParam;if(A){var x=n("#verification-code-form");if(0!==x.length){var y=null,k=!1;a.capabilities.android?(f=f.map(function(a){return a.isEnabled().then(function(b){return b?a.registerListener(h).then(function(a){return a}):{}})}),l.all(f).then(function(a){var b=[],c={};a.forEach(function(a){a.handlerCapability&&b.push(a.handlerCapability);a.handlerQueryParams&&n.extend(c,a.handlerQueryParams)});
a={arb:A,mode:"page_ajax",sendClientDrivenOtp:!0,capabilities:b.join()};n.extend(a,c);a=z.location.origin+"/ap/cvf/request?"+n.param(a);p(a)})):(l=z.location.origin+"/ap/cvf/request?"+n.param({arb:A,mode:"page_ajax",sendClientDrivenOtp:!0}),p(l))}}}});"use strict";
P.when("A","ready").register("codeResendTimer",function(a){function l(m,e,f,d,c,h){var l=(new Date).getTime();h&&(clearInterval(b),window.localStorage.removeItem("icaCVFTimeId"));b=setInterval(function(){var g=(new Date).getTime()-l,p=m-g;h&&window.localStorage.setItem("icaCVFTimeId",p);0>=p?(clearInterval(b),h&&window.localStorage.removeItem("icaCVFTimeId"),h?(a.$("#"+d).hide(),a.$("#"+c).show()):a.$("#"+c).html(f)):(g=e.split(" +timeleft+ "),h?(p=(new Date(p)).toISOString().slice(14,19),g=g[0].split('"').join("")+
p+g[1].split('"').join("")):g=g[0].split('"').join("")+Math.floor(p/1E3)+g[1].split('"').join(""),a.$("#"+d).html(g))},100)}var b;return{createTimer:function(a,b,f,d,c,h){return new l(a,b,f,d,c,h)},showTimer:function(){a.$("#cvf-resend-link").hide();a.$("#cvf-resend-text").removeClass("cvf-hidden")}}});"use strict";
P.when("A","cvfFormDataGenerator","ready").execute(function(a,l){var b=a.$;b(".cvf-widget-btn-val").click(function(a){var e=b(a.target).closest(".cvf-widget-form");a=l.getNameValue(b(a.target));e.append('\x3cinput type\x3d"hidden" name\x3d"'+a.name+'" value\x3d"'+a.value+'"\x3e').submit()})});"use strict";
P.when("A","cvfVersion","cvfFormDataGenerator","cvfInputValidator","ready").register("cvf",function(a,l,b,m){function e(e){function f(b){"string"===typeof k.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uex("ld",k.options.widgetMetricsScope,{wb:1});k.options.spinnerTarget&&k.options.spinnerTarget.hide();if(b.hasOwnProperty("error"))a.trigger(v.error,b.error);else if(b.redirectUrl)window.location=b.redirectUrl;else if(b.redirect){a.trigger(v.success,b.token,b.status,b.redirect);
if(k.options.showICALoadingAnimationOnSuccess){var c=d("#in-context-auth-loading-animation").prop("outerHTML");r.html(c)}k.options.autoDestroy?k.destroy():(d(".cvf-widget-alert").hide(),b.status?d(".cvf-widget-status-success").show():d(".cvf-widget-status-error").show(),y());a.trigger("cvf:verification:complete",b.status);r.find(".cvf-widget-btn").unbind("click",p);r.find(".cvf-widget-btn-val").unbind("click",p);a.off(v.success);a.off(v.error);a.off(v.content)}else r.html(b.replace(/<form/g,"\x3cdiv").replace(/<\/form/g,
"\x3c/div")),c=d(".cvf-widget-form-keep").clone().empty(),b=d(".cvf-widget-form-keep").children().clone(!0,!0),c=(new String(c.prop("outerHTML"))).replace(/<div/g,"\x3cform").replace(/<\/div/g,"\x3c/form"),d(".cvf-widget-form-keep").replaceWith(c),d(".cvf-widget-form-keep").html(b),w(),a.trigger(v.content)}function p(c,e,g){c.preventDefault();d(".cvf-widget-alert").hide();k.options.spinnerTarget&&k.options.spinnerTarget.show();var h=b.retrieveFormData(c.target,g);if(q()){if(k.options.showICAClaimUIOnClickChangeLink){k.options.showICAClaimUIOnClickChangeLink=
!1;k.options.spinnerTarget&&k.options.spinnerTarget.hide();c=d("#change-signin-claim-link-id").val();a.ajax(c,{method:"GET",dataType:"html",success:function(b){a.trigger("in-context-auth-content-update-event",b)},error:function(){d("#cvf-change-contact-link").hide();console.error("AJAX request to /ax/claim/ica failed.",this.error)}});return}if(g)r.find(".cvf-widget-input").removeClass("cvf-widget-input-error");else if(g=m.getValidationResult(h.form),g.inactiveAlerts.forEach(function(a){a.hide()}),
g.activeAlerts.forEach(function(a){a.show()}),g.isValid)r.find(".cvf-widget-input").removeClass("cvf-widget-input-error");else{k.options.spinnerTarget&&k.options.spinnerTarget.hide();r.find(".cvf-widget-input").addClass("cvf-widget-input-error");t();u();return}}g=h.inputData.serializeArray();e&&g.push(b.getNameValue(c.target));a.ajax(B+h.requestPath,{method:"POST",params:g,success:f,error:x})}function n(a){13===a.keyCode&&p(a)}function q(){return 0<r.find('input[name\x3d"is_in_context_auth"]').length}
function t(){r.find('input[name\x3d"code"]').focus()}function u(){r.find('input[name\x3d"code"]').keypress(n)}function w(){r.find(".cvf-widget-btn").click(function(a){p(a,!1)});r.find(".cvf-widget-btn-val").click(function(a){p(a,!0)});q()||t();u();r.find(".cvf-widget-v2-link-resend").click(function(a){p(a,!1,!0)});r.find("#cvf-signin-with-password").click(function(a){a.preventDefault();r.find("#cvf-signin-with-password-instead-form").submit()});r.find(".cvf-widget-v2-change-contact-link").click(function(a){k.options.showICAClaimUIOnClickChangeLink=
!0;p(a,!1)})}function A(b){return function(c,d,e){"timeout"!==d||3<=C?a.trigger(v.error,e):a.delay(b,10*C++)}}function x(b,c,d){k.options.spinnerTarget&&k.options.spinnerTarget.hide();a.trigger(v.error,d)}function y(){d.each(r.find("input"),function(a,b){a=d(b);a.attr("disabled","disabled");a.hasClass("a-input-text")?a.addClass("a-form-disabled"):a.hasClass("a-button-input")?a.closest(".a-button").addClass("a-button-disabled"):a.closest(".a-input-text-wrapper").length&&a.closest(".a-input-text-wrapper").addClass("a-form-disabled")});
d.each(r.find("a"),function(a,b){a=d(b);a.hasClass("cvf-widget-link-disable-target")&&a.addClass("cvf-link-disabled")})}var k=this;h++;var v={success:"cvf:"+h+":success",error:"cvf:"+h+":error",content:"cvf:"+h+":content"};k.options={};d.extend(k.options,c,e);(function(a){if(1!==d(a.target).length)throw Error("The CVF widget requires a unique element.");if(!d.isFunction(a.onSuccess))throw Error("The CVF widget requires a success callback function.");if(!d.isFunction(a.onError))throw Error("The CVF widget requires an error callback function.");
})(k.options);var B=k.options.server,r=d(k.options.target);a.on(v.success,k.options.onSuccess);a.on(v.error,k.options.onError);a.on(v.content,k.options.onContent);k.start=function(){var b=B+"/ap/cvf/request.embed",c=k.options.requestToken,e=k.options.requestArbToken,g=k.options.associationHandle,h=k.options.language,m=0===d.trim(c).length,n=0===d.trim(e).length;if(m&&n)throw Error("The CVF widget requires a request token or arb token.");m=0!==d.trim(g).length;var p=0!==d.trim(h).length,q={};n?q.requestToken=
c:q.arb=e;q.CVFVersion=l.version;q.AUIVersion=P.AUI_BUILD_DATE;p&&(q.language=h);m&&(q["openid.assoc_handle"]=g);"string"===typeof k.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uet("bb",k.options.widgetMetricsScope,{wb:1});a.ajax(b,{method:"GET",params:q,success:f,error:A(k.start)})};k.destroy=function(){r.html("")};w();var C=0;k.options.autoStart&&k.start()}function f(a){return new e(a)}var d=a.$,c={server:"",target:void 0,requestToken:void 0,requestArbToken:void 0,onSuccess:void 0,
onError:void 0,onContent:function(){},spinnerTarget:void 0,autoStart:!0,autoDestroy:!0,widgetMetricsScope:void 0,associationHandle:void 0,language:void 0,showICALoadingAnimationOnSuccess:!1,showICAClaimUIOnClickChangeLink:!1},h=0;a.on("cvf:verification:request",function(b){var c=d("#"+b),e=c.data("token"),h=c.data("spinnerId");h=d("#"+h);f({target:c,spinnerTarget:h,requestToken:e,onSuccess:function(c,d,e){a.trigger("cvf:verification:complete:"+b,c,d,e)},onError:function(c){a.trigger("cvf:verification:error:"+
b,c)},autoStart:!0,autoDestroy:!1})});return{create:f}});"use strict";
P.when("A","ready").register("cvfFormDataGenerator",function(a){var l=a.$;return{retrieveFormData:function(a,m){a=l(a).closest(".cvf-widget-form");m&&(a=l(".cvf-widget-form-resend"));return{requestPath:a.data("use-only-form-action")?a.attr("action"):"/ap/cvf/"+a.attr("action")+".embed",inputData:a.find(".cvf-widget-input,.cvf-widget-hidden-fields,.cvf-widget-input :input"),form:a}},getNameValue:function(a){a=l(a);var b=a.attr("name");b||(b=a.closest(".cvf-widget-btn-val").attr("data-name"));var e=
a.attr("value");e||(e=a.closest(".cvf-widget-btn-val").attr("data-value"));return{name:b,value:e}}}});"use strict";
P.when("A","cvf","ready").execute(function(a,l){var b=a.$;b(document).ready(function(){function a(a,b,c){window.location=c;console.log("Client Side: "+a)}function e(a){console.log(a)}var f=b(".cvf-widget-spinner"),d=b("#cvf-widget-content");if(1===d.length){var c=b('[name\x3d"requestToken"]').first().attr("value");l.create({target:d,spinnerTarget:f,requestToken:c,onSuccess:a,onError:e,autoStart:!1})}})});"use strict";
P.when("A","ready").register("phoneFormField",function(a){function l(){a:{for(var a=b("select[name\x3d'cvf_phone_cc']").val()||"",d=0;d<e.length;d++){var c=e[d];if(a.toUpperCase()===c){b("#mobileClaimDisclosureMessageV2").removeClass("a-hidden aok-hidden").show();b("#mobileClaimDisclosureMessage").addClass("aok-hidden").hide();b("#mobileClaimDisclosureMessageRelaxed").addClass("aok-hidden").hide();break a}}for(d=0;d<m.length;d++)if(c=m[d],a.toUpperCase()===c){b("#mobileClaimDisclosureMessage").removeClass("a-hidden aok-hidden").show();
b("#mobileClaimDisclosureMessageV2").addClass("aok-hidden").hide();b("#mobileClaimDisclosureMessageRelaxed").addClass("aok-hidden").hide();break a}b("#mobileClaimDisclosureMessageRelaxed").removeClass("a-hidden aok-hidden").show();b("#mobileClaimDisclosureMessage").addClass("aok-hidden").hide();b("#mobileClaimDisclosureMessageV2").addClass("aok-hidden").hide()}}var b=a.$,m=["CA","FR"],e=["US"];0<b("select[name\x3d'cvf_phone_cc']").length&&0<b("#mobileClaimDisclosureMessage").length&&0<b("#mobileClaimDisclosureMessageRelaxed").length&&
0<b("#mobileClaimDisclosureMessageV2").length&&(l(),b("select[name\x3d'cvf_phone_cc']").change(l))});"use strict";P.when("A","ready").execute(function(a){function l(a){var b=a.value.match(m);b&&1===b.length?a.setAttribute("aria-invalid","false"):a.setAttribute("aria-invalid","true")}function b(a){a.addEventListener("change",function(b){l(a)})}var m=/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;a=a.$("input[id\x3d'cvfEmail']");a.length&&(b(a[0]),l(a[0]))});"use strict";
P.when("A").execute(function(a){a.declarative("auth-popup","click",function(a){var b=a.data;a=a.$target.closest("a")[0];(b=window.open(a.href,a.target,b.windowOptions))&&b.focus()})});P.register("android-sms-otp-parser",function(){return{parseOtpCode:function(a){if(a&&(a=a.match(/(([\s\S]*[^0-9])|(^))([0-9]{4,6})[^0-9][\s\S]*[a-zA-Z0-9+\\\/]{11}/)||[],0<a.length))return a[4]}}});
P.when("A","mobile-auth-platform","3p-promise","android-sms-otp-parser","cvf-client-side-counters-util","ready").register("sms-retriever-handler",function(a,l,b,m,e){function f(a){(h=a.isSupported)?e.incrementCounter(c.ENABLED):e.incrementCounter(c.DISABLED);q={appHash:a.appHash}}function d(){return new b(function(a){q?a(q):l.isSmsRetrieverEnabled(function(b){f(b);a(q)})})}var c=Object.freeze({ENABLED:"SmsRetrieverEnabled",DISABLED:"SmsRetrieverDisabled",SMS_LISTENER_FAILED:"SmsRetrieverListenerFailedToRegister",
RECEIVED_INVALID_SMS:"SmsRetrieverListenerReceivedInvalidSms",RECEIVED_VALID_SMS:"SmsRetrieverListenerReceivedValidSms"}),h=null,q=null;return{isEnabled:function(){return new b(function(a){null!==h?a(h):l.isSmsRetrieverEnabled(function(b){f(b);a(h)})})},registerListener:function(a){return new b(function(b){l.registerMAPSmsReceiver(function(b){b.isRegistered?(b=m.parseOtpCode(b.sms))?(e.incrementCounter(c.RECEIVED_VALID_SMS),a(b)):e.incrementCounter(c.RECEIVED_INVALID_SMS):e.incrementCounter(c.SMS_LISTENER_FAILED)});
d().then(function(a){h?b({handlerCapability:"smsRetriever",handlerQueryParams:a}):b({})})})}}});"use strict";
P.when("A","a-spinner","ready").execute(function(a,l){function b(){f(".otp-input-box").attr("disabled","disabled");f("input[name\x3d'code']").val(m());(null!==f(".otp-input-box-container").data("isembed")?f(".otp-input-box-container").data("isembed"):1)?f(".cvf-widget-btn-verify").click():(a.capabilities.isAmazonApp||l("#otp-input-spinner").show(),f("#verification-code-form").submit())}function m(){var a="";f("input[name^\x3dotc]").each(function(b){a+=f(this).val()});return a}function e(){f(".cvf-widget-alert").is(":visible")&&
(f(".otp-input-box").removeClass("otp-input-box-alert"),f(".cvf-widget-alert").hide())}var f=a.$,d=/^\d+$/;a.declarative("otp-inputbox-handler","focusin",function(a){a=a.$target;a.is(".otp-input-box")&&(a.attr("name").match("otc-1")||""===a.prev().val()&&a.prev().focus())});a.declarative("otp-inputbox-handler","keyup",function(a){var c=a.$event;a=a.$target;a.is(".otp-input-box")&&(c=c.which||c.keyCode,-1===[16,9,224,18,17].indexOf(c))&&(-1!==[8,37,46].indexOf(c)?a.prev()&&!a.attr("name").match("otc-1")&&
(a.val(""),a.prev().select()):d.test(a.val())?a.attr("name").match("otc-6")?b():a.next()&&(e(),a.next().select()):a.val(""))});f(".otp-input-box").live("input",function(a){a=f(a.target);var c=a.val();e();if(1!==c.length)for(var d=0;d<c.length;d++){a.val(c.charAt(d));if(a.attr("name").match("otc-6")){b();break}a=a.next();a.focus()}});a.declarative("otp-inputbox-handler","click",function(){f("input[name^\x3dotc]").each(function(a){""===f(this).val()&&f(this).focus()})})});"use strict";
P.when("A","ready").execute(function(a){function l(a,b){b=Array.from((new Intl.NumberFormat(b,{useGrouping:!1})).format(9876543210)).reverse();var e=new Map(b.map(function(a,b){return[a,b]}));return a.split("").map(function(a){return e.has(a)?e.get(a):a}).join("")}a=a.$;var b=["ar-AE-u-nu-arab"];a("#ap_email, #ap_email_login, #auth-pv-enter-code, #cvf-input-code").keyup(function(){if(this.value){var a=this;b.map(function(b){a.value=l(a.value,b)})}})});